server:
  port: 8080

spring:

  # datasource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/halodb?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: root

  # jpa根据entity自动建表
  jpa:
    hibernate:
    # 有表就不创建,只更新,无表创表
      ddl-auto: update
    # 显示建表语句
    show-sql: true
    # 格式化SQL语句
    properties:
      hibernate:
        format_sql: true

  data:
    jpa:
      repositories:
        bootstrap-mode: default


#  flyway:
#    enabled: false



# 日志
logging:
  level:
    com.origami.haloblog: debug

